<?xml version="1.0" encoding="utf-8"?><Database Name="dinhan2509_" Class="MydbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql.bsite.net\MSSQL2016;Initial Catalog=dinhan2509_;User ID=dinhan2509_" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dinhan2509_ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="First_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Last_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Account_Cart" Member="Carts" ThisKey="ID" OtherKey="Account_id" Type="Cart" />
      <Association Name="Account_Check_out" Member="Check_outs" ThisKey="ID" OtherKey="Account_id" Type="Check_out" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Account_Cart" Member="Account" ThisKey="Account_id" OtherKey="ID" Type="Account" IsForeignKey="true" />
      <Association Name="Product_Cart" Member="Product" ThisKey="Product_id" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Check_out" Member="Check_outs">
    <Type Name="Check_out">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Account_username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cart_total" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Voucher" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Shipping_fee" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Account_Check_out" Member="Account" ThisKey="Account_id" OtherKey="ID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Product_image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Madein" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Product_Cart" Member="Carts" ThisKey="ID" OtherKey="Product_id" Type="Cart" />
    </Type>
  </Table>
</Database>